project:
  name: quickstart-wordpress-serverless
  owner: saif.ali@sudoconsultants.com
  package_lambda: false
  shorten_stack_name: true
  s3_regional_buckets: true
  regions:
    - ca-central-1
    - us-west-1
  s3_bucket: ""
  parameters:
    VPCCIDR: 10.0.0.0/16
    PrivateSubnet1CIDR: 10.0.0.0/19
    PrivateSubnet2CIDR: 10.0.32.0/19
    PrivateSubnet3CIDR: 10.0.64.0/19
    PublicSubnet1CIDR: 10.0.96.0/20
    PublicSubnet2CIDR: 10.0.128.0/20
    PublicSubnet3CIDR: 10.0.160.0/20
    DBName: $[taskcat_random-string]db
    DBUsername: "override"
    DBPassword: $[taskcat_genpass_16A]
    QSS3BucketName: $[taskcat_autobucket]
    QSS3BucketRegion: $[taskcat_current_region]
tests:
  new-vpc-wordpress-2az-ssl:
    template: templates/main-entrypoint-new-vpc.template.yaml
    parameters:
      NumberOfAZs: "2"
      AvailabilityZones: $[taskcat_genaz_2]
      UseSSL: "true"
      DomainName: "override"
      HostedZoneID: "override"
    regions:
      - us-west-1
      - ca-central-1
  new-vpc-wordpress-2az:
    template: templates/main-entrypoint-new-vpc.template.yaml
    parameters:
      NumberOfAZs: "2"
      AvailabilityZones: $[taskcat_genaz_2]
      UseSSL: "false"
      DomainName: "override"
      HostedZoneID: "override"
    regions:
      - us-west-1
  new-vpc-wordpress-3az:
    template: templates/main-entrypoint-new-vpc.template.yaml
    parameters:
      NumberOfAZs: "3"
      AvailabilityZones: $[taskcat_genaz_3]
      UseSSL: "false"
      DomainName: "override"
      HostedZoneID: "override"
    regions:
      - ca-central-1
# taskcat test run -t new-vpc-wordpress-2az-ssl -n
# taskcat test run -t new-vpc-wordpress-3az -n

