general:
  s3_regional_buckets: true
project:
  name: quickstart-wordpress-serverless
  owner: saif.ali@sudoconsultants.com
  package_lambda: false
  regions:
    - us-west-1
  parameters:
    QSS3BucketName: $[taskcat_autobucket]
    QSS3BucketRegion: $[taskcat_current_region]

tests:
  # Sample command: taskcat test run -t newvpcwordpress2 -r us-west-1
  new-vpc-wordpress-2az:
    template: templates/master.template.yaml
    parameters:
      DBUserPassword: $[taskcat_genpass_16A]
      AvailabilityZones: $[taskcat_genaz_2]
      PrivateSubnet1CIDR: 10.0.0.0/19
      PrivateSubnet2CIDR: 10.0.32.0/19
      PublicSubnet1CIDR: 10.0.96.0/20
      PublicSubnet2CIDR: 10.0.128.0/20
      VPCCIDR: 10.0.0.0/16
      NumberOfAZs: '2'
      KeyPairName: wp-key
      RemoteAccessCIDR: 0.0.0.0/0
    regions:
    - us-west-1