---
AWSTemplateFormatVersion: "2010-09-09"
Description:
  This template creates a new VPC and deploys WordPress in a Serverless architecture. **WARNING** You will be billed for the AWS resources used if you create a stack from this template.
Metadata:
  LICENSE: Apache License Version 2.0
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Quickstart configuration
        Parameters:
          - QSS3BucketName
          - QSS3KeyPrefix
          - QSS3BucketRegion
      - Label:
          default: Network configuration
        Parameters:
          - VPCCIDR
          - NumberOfAZs
          - PrivateSubnet1ACIDR
          - PrivateSubnet2ACIDR
          - PrivateSubnet3ACIDR
          - PublicSubnet1CIDR
          - PublicSubnet2CIDR
          - PublicSubnet3CIDR
          - AvailabilityZones
          - KeyPairName
          - VPCTenancy
      - Label:
          default: Database configuration
        Parameters:
          - DBName
          - DBClusterName
          - DBUserName
          - DBUserPassword
          - DBMaxCapacity
          - DBMinCapacity
          - DBBackupRetentionPeriod
          - DBPreferredBackupWindow
      - Label:
          default: Container configuration
        Parameters:
          - ContainerImage
          - ContainerCpu
          - ContainerMemory
          - ContainerMaxSize
          - ContainerDesiredCapacity
          - ContainerMinSize
          - ALBAccessCIDR
      - Label:
          default: FileSystem configuration
        Parameters:
          - EFSFileSystemName
          - EFSProvisionedThroughputInMibps
          - EFSPerformanceMode
          - EFSThroughputMode
    ParameterLabels:
      QSS3BucketName:
        default: Quickstart S3 bucket name
      QSS3KeyPrefix:
        default: Quickstart S3 key prefix
      QSS3BucketRegion:
        default: Quickstart S3 bucket region
      ALBAccessCIDR:
        default: ALB access CIDR
      ContainerCpu:
        default: Container cpu
      ContainerDesiredCapacity:
        default: Container desired capacity
      ContainerImage:
        default: Container image
      ContainerMaxSize:
        default: Container max size
      ContainerMemory:
        default: Container memory
      ContainerMinSize:
        default: Container min size
      DBBackupRetentionPeriod:
        default: DB backup retention period
      DBClusterName:
        default: DB cluster name
      DBMaxCapacity:
        default: DB max capacity
      DBMinCapacity:
        default: DB min capacity
      DBName:
        default: DB name
      DBPreferredBackupWindow:
        default: DB preferred backup window
      DBUserName:
        default: DB user name
      DBUserPassword:
        default: DB user password
      PrivateSubnet1ACIDR:
        default: Private subnet 1 CIDR
      PrivateSubnet2ACIDR:
        default: Private subnet 2 CIDR
      PrivateSubnet3ACIDR:
        default: Private subnet 3 CIDR
      PublicSubnet1CIDR:
        default: Public subnet 1 CIDR
      PublicSubnet2CIDR:
        default: Public subnet 2 CIDR
      PublicSubnet3CIDR:
        default: Public subnet 3 CIDR
      VPCCIDR:
        default: VPC CIDR
      EFSProvisionedThroughputInMibps:
        default: EFS provisioned throughput in mibps
      EFSFileSystemName:
        default: EFS file system name
      EFSPerformanceMode:
        default: EFS performance mode
      EFSThroughputMode:
        default: EFS throughput mode
Parameters:
  QSS3KeyPrefix:
    AllowedPattern: ^([0-9a-zA-Z-.]+/)*$
    ConstraintDescription: The Quick Start S3 key prefix can include numbers, lowercase letters,
      uppercase letters, hyphens (-), and forward slashes (/).
    Default: quickstart-wordpress-serverless/
    Description: S3 key prefix that is used to simulate a directory for your copy of the 
      Quick Start assets. Keep the default prefix unless you are customizing 
      the template. Changing this prefix updates code references to point to 
      a new Quick Start location. This prefix can include numbers, lowercase 
      letters, uppercase letters, hyphens (-), and forward slashes (/). End with a forward slash. 
      See https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html 
      and https://aws-quickstart.github.io/option1.html.
    Type: String
  ALBAccessCIDR:
    Type: String
    Default: 0.0.0.0/0
    Description: Allowed CIDR block for external web access to the Application Load Balancer
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/([0-9]|[1-2][0-9]|3[0-2]))$"
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/x
  ContainerCpu:
    Type: String
    Default: "256"
    Description: ""
    AllowedValues: ["256", "512", "1024", "2048", "4096"]
  ContainerDesiredCapacity:
    Type: Number
    Default: "2"
    Description:
      Desired number of WordPress containers. This will set the number of
      containers when the scaling group is created, then the auto scaler will increase
      or decrease the current number of containers as the scaling events occur.
  ContainerImage:
    Type: String
    Default: "docker.io/wordpress:latest"
    Description: ""
  ContainerMaxSize:
    Type: Number
    Default: "12"
    Description:
      Maximum number of WordPress EC2 containers in the Auto Scaling group.
      It specifies the maximum number of replicas when scaling up.
  ContainerMemory:
    Type: String
    Default: "0.5GB"
    Description: ""
  ContainerMinSize:
    Type: Number
    Default: "1"
    Description:
      Minimum number of WordPress EC2 instances in the Auto Scaling group.
      It specifies the minimum number of replicas when scaling down.
  DBBackupRetentionPeriod:
    Type: Number
    Default: "7"
    Description: The number of days for which automatic DB snapshots are retained
    ConstraintDescription: Database backup retention period must be between 1 and 35 days
    MaxValue: "35"
    MinValue: "1"
  DBClusterName:
    Type: String
    Default: "myDBCluster"
    Description: Aurora DB Cluster Name
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    MaxLength: "64"
    MinLength: "5"
  DBMaxCapacity:
    Type: Number
    Default: "16"
    Description: Aurora serverless DB max capacity
  DBMinCapacity:
    Type: Number
    Default: "2"
    Description: Aurora serverless DB min capacity
  DBName:
    Type: String
    Default: "myDatabase"
    Description: Database Name
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    MaxLength: "64"
    MinLength: "5"
  DBPreferredBackupWindow:
    Type: String
    Default: ""
    Description: "(Optional) Preferred backup window"
    AllowedPattern: "^(|([0-1][0-9]|2[0-3]):[0-5][0-9]-([0-1][0-9]|2[0-3]):[0-5][0-9])$"
    ConstraintDescription: Preferred backup window must be left blank or in the form of HH:MM-HH:MM
  DBUserName:
    Type: String
    Default: admin
    Description: Database user name
  DBUserPassword:
    Type: String
    Description: Database user password
    MaxLength: "41"
    MinLength: "8"
    NoEcho: "True"
  EFSProvisionedThroughputInMibps:
    Type: Number
    Default: 0
    Description: ""
    MinValue: 0
    MaxValue: 1024
  EFSFileSystemName:
    Type: String
    Default: myFileSystem
    Description: EFS FileSystem Name
  EFSPerformanceMode:
    Type: String
    Default: generalPurpose
    Description: EFS FileSystem Performance mode
    AllowedValues: [generalPurpose, maxIO]
  EFSThroughputMode:
    Type: String
    Default: bursting
    Description: EFS FileSystem Throughput mode
    AllowedValues: [bursting, provisioned]

# Submodule parameters
  AvailabilityZones:
    Description: List of Availability Zones to use for the subnets in the VPC.
    Type: 'List<AWS::EC2::AvailabilityZone::Name>'
  KeyPairName:
    Description: Name of an existing public/private key pair, which allows you to securely connect to your instance
      after it launches.
    Type: 'AWS::EC2::KeyPair::KeyName'
  PrivateSubnet1ACIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.0.0/19
    Description: CIDR block for private subnet 1A located in Availability Zone 1
    Type: String
  PrivateSubnet2ACIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.32.0/19
    Description: CIDR block for private subnet 2A located in Availability Zone 2
    Type: String
  PrivateSubnet3ACIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.64.0/19
    Description: CIDR block for private subnet 3A located in Availability Zone 3
    Type: String
  # PrivateSubnet4ACIDR:
  #   AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
  #   ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
  #   Default: 10.0.96.0/19
  #   Description: CIDR block for private subnet 4A located in Availability Zone 4
  #   Type: String
  PublicSubnet1CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.128.0/20
    Description:
      CIDR block for the public DMZ subnet 1 located in Availability Zone
      1
    Type: String
  PublicSubnet2CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.144.0/20
    Description:
      CIDR block for the public DMZ subnet 2 located in Availability Zone
      2
    Type: String
  PublicSubnet3CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.160.0/20
    Description:
      CIDR block for the public DMZ subnet 3 located in Availability Zone
      3
    Type: String
  # PublicSubnet4CIDR:
  #   AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
  #   ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
  #   Default: 10.0.176.0/20
  #   Description:
  #     CIDR block for the public DMZ subnet 4 located in Availability Zone
  #     4
  #   Type: String
  VPCTenancy:
    AllowedValues:
      - default
      - dedicated
    Default: default
    Description: The allowed tenancy of instances launched into the VPC.
    Type: String
  QSS3BucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: The Quick Start bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a 
      hyphen (-).
    Default: aws-quickstart
    Description: Name of the S3 bucket for your copy of the Quick Start assets. 
      Keep the default name unless you are customizing the template. 
      Changing the name updates code references to point to a new Quick 
      Start location. This name can include numbers, lowercase letters, 
      uppercase letters, and hyphens, but do not start or end with a hyphen (-). 
      See https://aws-quickstart.github.io/option1.html.
    Type: String
  QSS3BucketRegion:
    Default: 'us-east-1'
    Description: 'AWS Region where the Quick Start S3 bucket (QSS3BucketName) is 
    hosted. Keep the default Region unless you are customizing the template. 
    Changing this Region updates code references to point to a new Quick Start location. 
    When using your own bucket, specify the Region. 
    See https://aws-quickstart.github.io/option1.html.'
    Type: String
  VPCCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.0.0/16
    Description: CIDR Block for the VPC.
    Type: String
  NumberOfAZs:
    Type: String
    AllowedValues: ['2', '3']
    Default: '2'
    Description: Number of Availability Zones to use in the VPC. This must match the value entered for the AvailabilityZones parameter.
Conditions:
  UsingDefaultBucket: !Equals [!Ref QSS3BucketName, 'aws-quickstart']
  3AZDeployment: !Equals [!Ref NumberOfAZs, '3']
Resources:
# Create new VPC
  VPCStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub
        - https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}submodules/quickstart-aws-vpc/templates/aws-vpc.template
        - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
          S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
      Parameters:
        VPCCIDR: !Ref 'VPCCIDR'
        VPCTenancy: !Ref 'VPCTenancy'
        KeyPairName: !Ref 'KeyPairName'
        NumberOfAZs: !Ref 'NumberOfAZs'
        AvailabilityZones: !Join [ ',', !Ref 'AvailabilityZones' ]
        PrivateSubnet1ACIDR: !Ref 'PrivateSubnet1ACIDR'
        PrivateSubnet2ACIDR: !Ref 'PrivateSubnet2ACIDR'
        PrivateSubnet3ACIDR: !Ref 'PrivateSubnet3ACIDR'
        PublicSubnet1CIDR: !Ref 'PublicSubnet1CIDR'
        PublicSubnet2CIDR: !Ref 'PublicSubnet2CIDR'
        PublicSubnet3CIDR: !Ref 'PublicSubnet3CIDR'
# Deploy a wordpress stack
  WordPressStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/wordpress.template.yaml
        - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
          S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
      Parameters:
        QSS3BucketName: !Ref QSS3BucketName
        QSS3KeyPrefix: !Ref QSS3KeyPrefix
        QSS3BucketRegion: !Ref QSS3BucketRegion
        ALBAccessCIDR: !Ref ALBAccessCIDR
        ContainerCpu: !Ref ContainerCpu
        ContainerDesiredCapacity: !Ref ContainerDesiredCapacity
        ContainerImage: !Ref ContainerImage
        ContainerMaxSize: !Ref ContainerMaxSize
        ContainerMemory: !Ref ContainerMemory
        ContainerMinSize: !Ref ContainerMinSize
        DBBackupRetentionPeriod: !Ref DBBackupRetentionPeriod
        DBClusterName: !Ref DBClusterName
        DBMaxCapacity: !Ref DBMaxCapacity
        DBMinCapacity: !Ref DBMinCapacity
        DBName: !Ref DBName
        DBPreferredBackupWindow: !Ref DBPreferredBackupWindow
        DBUserName: !Ref DBUserName
        DBUserPassword: !Ref DBUserPassword
        EFSProvisionedThroughputInMibps: !Ref EFSProvisionedThroughputInMibps
        EFSFileSystemName: !Ref EFSFileSystemName
        EFSPerformanceMode: !Ref EFSPerformanceMode
        EFSThroughputMode: !Ref EFSThroughputMode
        PrivateSubnet1ID: !GetAtt VPCStack.Outputs.PrivateSubnet1AID
        PrivateSubnet2ID: !GetAtt VPCStack.Outputs.PrivateSubnet2AID
        PrivateSubnet3ID: !If [3AZDeployment, !GetAtt VPCStack.Outputs.PrivateSubnet3AID, '']
        PublicSubnet1ID: !GetAtt VPCStack.Outputs.PublicSubnet1ID
        PublicSubnet2ID: !GetAtt VPCStack.Outputs.PublicSubnet2ID
        PublicSubnet3ID: !If [3AZDeployment, !GetAtt VPCStack.Outputs.PublicSubnet3ID, '']
        VPCID: !GetAtt VPCStack.Outputs.VPCID
Outputs:
  ApplicationLoadBalancerDNSName:
    Description: "The URL of the ELB. Point your domain to it by using a CNAME/ALIAS DNS record"
    Value: !GetAtt WordPressStack.Outputs.ApplicationLoadBalancerDNSName